### ISSUE TITLE
cli.parse() fails to fail on required arg

### ISSUE THREAD

**Issue by eschwartz** [four43/admiral-cli#13]
Here's the code:

```js
var cli = new Cli();
cli.
	option({
		name: 'configFile',
		description: 'Path to JSON config for docker compose template',
		shortFlag: '-c',
		length: 1,
		required: true
	}).
	option({
		name: 'outFile',
		shortFlag: '-o',
		length: '+',
		required: false
	}).
	flag({
		name: 'help',
		shortFlag: '-h',
		longFlag: '--help'
	});

cli.parse();
```

If I run this script without any arguments, it does *not* throw an error - I would expect it to, as the `configFile` options is required.

**Comment by four43** [comment]
Fixed via https://github.com/four43/admiral-cli/pull/16, specifically https://github.com/four43/admiral-cli/blob/master/test/OptionsTest.js#L242 tests the problem
