### ISSUE TITLE
New CLI Option: allowExtraArgs

### ISSUE THREAD

**Issue by eschwartz** [four43/admiral-cli#9]
The current behavior of `parse()` throws an error if extra arguments are passed to the script, which are not specified in an `option()` call:

```js
// script called with `--foo faz --bar baz`

cli.option('foo', 'What the foo?', '--foo');
cli.parse();  // [InvaliInputError] Flag --bar is unknown
```

This is ok for default behavior, but it would be nice to disable this via `allowExtraArgs`:

```js
// script called with `--foo faz --bar baz`

var cli = new Cli({
  allowExtraArgs: true   // default is `false`
});

cli.option('foo', 'What the foo?', '--foo');
cli.parse();  // no prob, bob

cli.params.foo == 'faz';   // true
```

**Comment by four43** [comment]
Agreed, that should be a quick one.

**Comment by four43** [comment]
@eschwartz - That should do it. Closing!
